#!/bin/sh
#
# Launch kitty under Asahi M1 GPU drivers
#
# This is a hack around bypassing the OpenGL 3.3 requirement as per Martin
# kitty isn't actually using any of the features past 3.1+ so its silly for
# them to mandate it.
#
# Warning however, you ARE disabling 3.3+ for anything started from within kitty
# That's why we're using this wrapper script and _NOT_ putting it in say your ~/.profile
#
# see suggestoin from Hector Martin here:
# https://old.reddit.com/r/AsahiLinux/comments/zqejue/kitty_not_working_with_mesaasahiedge/j0y1vp3
#

exec MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 kitty
